"use strict";
exports.__esModule = true;
var colegio_1 = require("./colegio");
var examenOral_1 = require("./examenOral");
var examenEscrito_1 = require("./examenEscrito");
var alumno_1 = require("./alumno");
var examen1 = new examenOral_1.ExamenOral("matematica", 4);
var alumno1 = new alumno_1.Alumno("carla", 21321, 28);
alumno1.agregarExamen(examen1);
var examen2 = new examenEscrito_1.ExamenEscrito("matematica", 8);
alumno1.agregarExamen(examen2);
console.log(examen1.tipoExamen());
console.log(examen2.tipoExamen());
examen2.CriterioAprobacion();
alumno1.sacarPromedio();
var examen3 = new examenOral_1.ExamenOral("matematica", 8);
var alumno2 = new alumno_1.Alumno("juan", 21213321, 24);
alumno2.agregarExamen(examen3);
var examen4 = new examenEscrito_1.ExamenEscrito("lengua", 3);
alumno2.agregarExamen(examen4);
var colegio = new colegio_1.Colegio("san jose");
colegio.agregarAlumno(alumno1);
colegio.agregarAlumno(alumno2);
colegio.sacarPromedioAlumnos();
console.log(colegio.getpromedioAlumnos());
console.log(colegio.getAlumnos());
