"use strict";
exports.__esModule = true;
var audio_1 = require("./audio");
var reproductor_1 = require("./reproductor");
var reproductor2_1 = require("./reproductor2");
var cancion1 = new audio_1.Audio(3, "Save your tears", 3.35, "Thw Weeknd");
var cancion2 = new audio_1.Audio(4, "IDGAF", 3.37, "Dua Lipa");
var reproductor = new reproductor_1.Reproductor();
reproductor.prender();
reproductor.agregarCancion(cancion1);
reproductor.agregarCancion(cancion2);
console.log(reproductor.getCancionActual());
reproductor.cancionAnterior();
console.log(reproductor.getCancionActual());
reproductor.cancionAnterior();
console.log(reproductor.getCancionActual());
reproductor.cancionAnterior();
console.log(reproductor.getCancionActual());
reproductor.cancionAnterior();
console.log(reproductor.getCancionActual());
console.log(reproductor.getCantidadPistas());
var repr2 = new reproductor2_1.Reproductor2();
repr2.prender();
repr2.abrirApp();
repr2.cancionAnterior();
console.log(repr2.getCancionActual());
console.log(repr2.getDuracion());
